### ISSUE TITLE
Click does not set input value

### ISSUE THREAD

**Issue by master-elodin** [ritz078/react-fuzzy-search#25]
If an option gets clicked, `input.value` does not get set as one would expect.

**Comment by PatrickDesign** [comment]
Is this feature still desired?

**Comment by master-elodin** [comment]
Yeah, it's still desired. I've had a PR open for it for the last two years :) 
https://github.com/ritz078/react-fuzzy-search/issues/25

**Comment by PatrickDesign** [comment]
https://github.com/ritz078/react-fuzzy-search/pull/45

**Comment by ritz078** [comment]
Sorry I didn't address this earlier. I think that in theory this component should always be controlled.

Why ?

- The user can decide what value to fill in the input field based on the selected result. It might not always be a fixed property. To fix this we will have to provide an additional prop that we should avoid.
- It's a good principle that form elements are controlled so that a single data source handles the value. This makes prefilling the data in the input field easier.

Having said that, I think we should fix https://github.com/ritz078/react-fuzzy-search/issues/27 so that it always behaves a sa controlled component. What does everyone think ?

Again I am sorry for jumping in late on this one.

**Comment by PatrickDesign** [comment]
> The user can decide what value to fill in the input field based on the selected result.
We do not currently allow the input value to be set by the user, do we?

**Comment by ritz078** [comment]
> We do not currently allow the input value to be set by the user, do we?

So we should add a prop that can directly take the value that needs to be shown from the user instead of handling it ourselves.

**Comment by PatrickDesign** [comment]
@ritz078 The fix for this issue has been moved to a simpler approach in https://github.com/ritz078/react-fuzzy-search/pull/52
